# Generated by Django 4.2.7 on 2023-11-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blog | Victor Kosmeniuk', max_length=255),
        ),
    ]
