# Generated by Django 4.2.7 on 2023-12-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
